version: '3'

services:
  openwrt:
    image: openwrt
    container_name: openwrt
    build:
      context: .
    volumes:
      - ${SOURCE_CODE_PATH}/openwrt:/work/openwrt
      - ${SOURCE_CODE_PATH}/lede:/work/lede
      - ${SOURCE_CODE_PATH}/passwall:/work/passwall
      - ${SOURCE_CODE_PATH}/openclash:/work/openclash
    network_mode: host
    privileged: true
